<a href="https://colab.research.google.com/github/Kadakol/ML/blob/master/MNIST_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from tensorflow.keras.datasets import mnist

In [0]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [0]:
train_images.shape

(60000, 28, 28)

In [0]:
test_images.shape

(10000, 28, 28)

In [0]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
train_labels.shape

(60000,)

In [0]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [0]:
test_labels.shape

(10000,)

In [0]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

In [0]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [0]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [0]:
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [0]:
def create_and_test_model(dropout_1, dropout_2, results):
    model = models.Sequential()
    model.add(layer = layers.Dense(256, activation="relu", input_shape=(28 * 28,)))
    model.add(layers.Dropout(dropout_1))
    model.add(layer = layers.Dense(64, activation="relu"))
    model.add(layers.Dropout(dropout_2))
    model.add(layers.Dense(10, activation="softmax"))
    model.compile(optimizer='rmsprop',
             loss='categorical_crossentropy',
             metrics=['accuracy'])
    model.fit(train_images, train_labels, epochs=25, batch_size=512, verbose=2)
    test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
    results.append((dropout_1, dropout_2, test_acc))

In [0]:
import numpy as np

results = []
dropouts = np.random.uniform(size=10, low=0, high=0.5)

print(dropouts)

for i in range(int(len(dropouts) / 2)):
    print("Running model with dropout_1 = {0} and dropout_2 = {1}".format(dropouts[i], dropouts[i + int(len(dropouts)/2)]))
    create_and_test_model(dropouts[i], dropouts[i + int(len(dropouts)/2)], results)
    
print("Results");
print('-' * 50)
for item in results:
    print('dropout_1 = {0}, dropout_2 = {1}, accuracy = {2}'.format(item[0], item[1], item[2]));
print('-' * 50)

[0.07476591 0.21307081 0.37153159 0.4438474  0.12997783 0.42272933
 0.28346966 0.32960557 0.15381767 0.41528648]
Running model with dropout_1 = 0.07476590974255592 and dropout_2 = 0.4227293273568066
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 60000 samples
Epoch 1/25
60000/60000 - 2s - loss: 0.5814 - acc: 0.8284
Epoch 2/25
60000/60000 - 2s - loss: 0.2497 - acc: 0.9288
Epoch 3/25
60000/60000 - 2s - loss: 0.1747 - acc: 0.9500
Epoch 4/25
60000/60000 - 2s - loss: 0.1367 - acc: 0.9611
Epoch 5/25
60000/60000 - 2s - loss: 0.1126 - acc: 0.9674
Epoch 6/25
60000/60000 - 2s - loss: 0.0966 - acc: 0.9722
Epoch 7/25
60000/60000 - 2s - loss: 0.0814 - acc: 0.9766
Epoch 8/25
60000/60000 - 2s - loss: 0.0737 - acc: 0.9785
Epoch 9/25
60000/60000 - 2s - loss: 0.0653 - acc: 0.9808
Epoch 10/25
60000/60000 - 2s - loss: 0.0584 - acc: 0.9821
Epoch 11/25
60000/60000 - 2s - loss: 0.0505 - acc: 0.9847
Epoch 12/25
60000/60000 - 2s - loss: 0.0456 - acc: 0.9863
Epoch 13/2

In [0]:
sorted(results, key=lambda x:x[2])

[(0.4438473992706803, 0.15381767429174759, 0.981),
 (0.37153158570880146, 0.3296055670703753, 0.9814),
 (0.07476590974255592, 0.4227293273568066, 0.9816),
 (0.129977832749072, 0.4152864773624046, 0.982),
 (0.21307081138809808, 0.2834696583798367, 0.9827)]